/**
 * tanglish.js — Complete Tanglish (Tamil in English Letters) Mapping & Transliteration
 * for VF Smart List
 */

// Exact dictionary for all catalog items across all categories (both English & Tanglish keys)
export const TANGLISH_DICTIONARY = {
  // ── Vegetables ───────────────────────────────────────
  'tomato': 'Thakkali',
  'thakkali': 'Thakkali',
  'potato': 'Urulaikizhangu',
  'urulaikizhangu': 'Urulaikizhangu',
  'onion': 'Vengayam',
  'vengayam': 'Vengayam',
  'garlic': 'Poondu',
  'poondu': 'Poondu',
  'ginger': 'Inji',
  'inji': 'Inji',
  'carrot': 'Carrot',
  'cabbage': 'Muttaikose',
  'muttaikose': 'Muttaikose',
  'cauliflower': 'Cauliflower',
  'broccoli': 'Broccoli',
  'spinach': 'Keerai',
  'keerai': 'Keerai',
  'peas': 'Pattani',
  'pattani': 'Pattani',
  'beans': 'Beans',
  'lady finger (okra)': 'Vendakkai',
  'lady finger': 'Vendakkai',
  'okra': 'Vendakkai',
  'vendakkai': 'Vendakkai',
  'vendaikkai': 'Vendakkai',
  'brinjal (eggplant)': 'Kathirikkai',
  'brinjal': 'Kathirikkai',
  'kathirikkai': 'Kathirikkai',
  'capsicum': 'Kudaimilagai',
  'kudaimilagai': 'Kudaimilagai',
  'kudai milagai': 'Kudaimilagai',
  'kudai milagaai': 'Kudaimilagai',
  'green chilli': 'Pachai Milagai',
  'pachai milagai': 'Pachai Milagai',
  'pachai milagaai': 'Pachai Milagai',
  'red chilli': 'Kaanja Milagai',
  'dry red chilli': 'Kaanja Milagai',
  'kaindha milagaai': 'Kaanja Milagai',
  'kaanja milagai': 'Kaanja Milagai',
  'bitter gourd': 'Pavakkai',
  'pavakkai': 'Pavakkai',
  'paavakkai': 'Pavakkai',
  'bottle gourd': 'Suraikkai',
  'suraikkai': 'Suraikkai',
  'sorakkai': 'Suraikkai',
  'ridge gourd': 'Peerkangai',
  'peerkangai': 'Peerkangai',
  'peerkkangkai': 'Peerkangai',
  'snake gourd': 'Pudalangai',
  'pudalangai': 'Pudalangai',
  'pudalangkai': 'Pudalangai',
  'ash gourd': 'Poosanikkai',
  'poosanikkai': 'Poosanikkai',
  'pumpkin': 'Manjal Poosani',
  'manjal poosani': 'Manjal Poosani',
  'sweet potato': 'Sakkaravalli Kizhangu',
  'sakkaravalli kizhangu': 'Sakkaravalli Kizhangu',
  'sarkkaravalli': 'Sakkaravalli Kizhangu',
  'yam': 'Senaikizhangu',
  'senaikizhangu': 'Senaikizhangu',
  'senaikizhungu': 'Senaikizhangu',
  'colocasia (taro)': 'Seppankizhangu',
  'colocasia': 'Seppankizhangu',
  'seppankizhangu': 'Seppankizhangu',
  'cheppankizhungu': 'Seppankizhangu',
  'radish': 'Mullangi',
  'mullangi': 'Mullangi',
  'beetroot': 'Beetroot',
  'turnip': 'Turnip',
  'corn': 'Cholam',
  'cholam': 'Cholam',
  'mushroom': 'Kaalan',
  'kaalan': 'Kaalan',
  'kaalaan': 'Kaalan',
  'spring onion': 'Vengayathaal',
  'vengayathaal': 'Vengayathaal',
  'vengayathal': 'Vengayathaal',
  'leek': 'Leeks',
  'leeks': 'Leeks',
  'celery': 'Celery',
  'cucumber': 'Vellarikkai',
  'vellarikkai': 'Vellarikkai',
  'vellarikai': 'Vellarikkai',
  'zucchini': 'Zucchini',
  'drumstick': 'Murungakkai',
  'murungakkai': 'Murungakkai',
  'raw banana': 'Vazhaikkai',
  'vazhaikkai': 'Vazhaikkai',
  'vazhakkai': 'Vazhaikkai',
  'raw papaya': 'Pappalikkai',
  'pappalikkai': 'Pappalikkai',
  'cluster beans': 'Kothavarangai',
  'kothavarangai': 'Kothavarangai',
  'kothavarankkai': 'Kothavarangai',
  'flat beans': 'Avaraikkai',
  'avaraikkai': 'Avaraikkai',
  'avarakkai': 'Avaraikkai',
  'fenugreek leaves': 'Vendhaya Keerai',
  'vendhaya keerai': 'Vendhaya Keerai',
  'shallots (small onion)': 'Chinna Vengayam',
  'shallots': 'Chinna Vengayam',
  'small onion': 'Chinna Vengayam',
  'chinna vengayam': 'Chinna Vengayam',
  'chayote (chow chow)': 'Chow Chow',
  'chow chow': 'Chow Chow',
  'french beans': 'French Beans',
  'palak (spinach)': 'Paalakeerai',
  'palak keerai': 'Paalakeerai',
  'mint leaves (pudina)': 'Pudina',
  'pudina': 'Pudina',
  'coriander leaves': 'Kothamalli',
  'kothamalli': 'Kothamalli',
  'curry leaves': 'Kariveppilai',
  'kariveppilai': 'Kariveppilai',
  'karuveppilai': 'Kariveppilai',

  // ── Fruits ───────────────────────────────────────────
  'mango': 'Maambazham',
  'maambazham': 'Maambazham',
  'apple': 'Aappil',
  'aappil': 'Aappil',
  'banana': 'Vazhaipazham',
  'vazhaipazham': 'Vazhaipazham',
  'vazhapazham': 'Vazhaipazham',
  'grapes': 'Dhraakshai',
  'dhraakshai': 'Dhraakshai',
  'thiratchai': 'Dhraakshai',
  'orange': 'Aaranju',
  'aaranju': 'Aaranju',
  'papaya': 'Pappaali',
  'pappaali': 'Pappaali',
  'pappali': 'Pappaali',
  'watermelon': 'Tharpoosani',
  'tharpoosani': 'Tharpoosani',
  'tharboosani': 'Tharpoosani',
  'muskmelon': 'Mulaambazham',
  'mulaambazham': 'Mulaambazham',
  'mulampazham': 'Mulaambazham',
  'pineapple': 'Annaasi',
  'annaasi': 'Annaasi',
  'annasi': 'Annaasi',
  'pomegranate': 'Maadhulai',
  'maadhulai': 'Maadhulai',
  'mathulai': 'Maadhulai',
  'guava': 'Koyyaa',
  'koyyaa': 'Koyyaa',
  'koyyapazham': 'Koyyaa',
  'sapota (chikoo)': 'Sapota',
  'sapota': 'Sapota',
  'chikoo': 'Sapota',
  'coconut': 'Thengai',
  'thengai': 'Thengai',
  'lemon': 'Elumichai',
  'elumichai': 'Elumichai',
  'lime': 'Pachai Elumichai',
  'pachai elumichai': 'Pachai Elumichai',
  'strawberry': 'Strawberry',
  'kiwi': 'Kiwi',
  'pear': 'Perikkaai',
  'perikkaai': 'Perikkaai',
  'pearikkai': 'Perikkaai',
  'peach': 'Peach',
  'plum': 'Plums',
  'plums': 'Plums',
  'cherry': 'Cherry',
  'fig': 'Athippazham',
  'figs': 'Athippazham',
  'athippazham': 'Athippazham',
  'athipazham': 'Athippazham',
  'dragon fruit': 'Dragon Pazham',
  'dragon pazham': 'Dragon Pazham',
  'avocado': 'Vennai Pazham',
  'vennai pazham': 'Vennai Pazham',
  'jackfruit': 'Palaappazham',
  'palaappazham': 'Palaappazham',
  'palabazham': 'Palaappazham',
  'custard apple': 'Seethaappazham',
  'seethaappazham': 'Seethaappazham',
  'seethapazham': 'Seethaappazham',
  'star fruit': 'Vilambi Pazham',
  'vilambi pazham': 'Vilambi Pazham',
  'passion fruit': 'Passion Fruit',
  'tamarind': 'Puli',
  'puli': 'Puli',
  'amla (gooseberry)': 'Nellikkai',
  'amla': 'Nellikkai',
  'gooseberry': 'Nellikkai',
  'nellikkai': 'Nellikkai',
  'dates': 'Perichampazham',
  'perichampazham': 'Perichampazham',
  'pericham pazham': 'Perichampazham',
  'litchi': 'Litchi',

  // ── Groceries ────────────────────────────────────────
  'rice': 'Arisi',
  'arisi': 'Arisi',
  'boiled rice': 'Puzhungal Arisi',
  'puzhungal arisi': 'Puzhungal Arisi',
  'raw rice': 'Pacharisi',
  'pacharisi': 'Pacharisi',
  'idli rice': 'Idli Arisi',
  'idli arisi': 'Idli Arisi',
  'basmati rice': 'Basmati Arisi',
  'basmati arisi': 'Basmati Arisi',
  'wheat': 'Godhumai',
  'godhumai': 'Godhumai',
  'wheat flour': 'Godhumai Maavu',
  'godhumai maavu': 'Godhumai Maavu',
  'maida / refined flour': 'Maida',
  'maida': 'Maida',
  'semolina / rava': 'Ravai',
  'rava': 'Ravai',
  'ravai': 'Ravai',
  'pearl millet': 'Kambu',
  'kambu': 'Kambu',
  'finger millet / ragi': 'Kezhvaragu',
  'ragi': 'Kezhvaragu',
  'kelvaragu': 'Kezhvaragu',
  'kelvaragu / ragi': 'Kezhvaragu',
  'sorghum / jowar': 'Cholam',
  'foxtail millet': 'Thinai',
  'thinai': 'Thinai',
  'little millet': 'Saamai',
  'saamai': 'Saamai',
  'samai': 'Saamai',
  'kodo millet': 'Varagu',
  'varagu': 'Varagu',
  'barnyard millet': 'Kuthiraivaali',
  'kuthiraivaali': 'Kuthiraivaali',
  'kuthiraivali': 'Kuthiraivaali',
  'oats': 'Oats',
  'flattened rice / poha': 'Aval',
  'poha': 'Aval',
  'aval': 'Aval',
  'corn flour': 'Chola Maavu',
  'cholam maavu': 'Chola Maavu',
  'gram flour / besan': 'Kadalai Maavu',
  'besan': 'Kadalai Maavu',
  'kadalai maavu': 'Kadalai Maavu',
  'rice flour': 'Arisi Maavu',
  'arisi maavu': 'Arisi Maavu',
  'urad flour': 'Ulundhu Maavu',
  'ulundhu maavu': 'Ulundhu Maavu',
  'toor dal': 'Thuvaram Paruppu',
  'thuvaram paruppu': 'Thuvaram Paruppu',
  'moong dal': 'Paasi Paruppu',
  'paasi paruppu': 'Paasi Paruppu',
  'green gram': 'Paasi Payaru',
  'paasi payaru': 'Paasi Payaru',
  'urad dal': 'Ulutham Paruppu',
  'ulutham paruppu': 'Ulutham Paruppu',
  'chana dal': 'Kadalai Paruppu',
  'kadalai paruppu': 'Kadalai Paruppu',
  'horse gram': 'Kollu',
  'kollu': 'Kollu',
  'masoor dal': 'Masoor Paruppu',
  'masoor paruppu': 'Masoor Paruppu',
  'white chickpeas': 'Vellai Kondaikadalai',
  'vellai kondaikadalai': 'Vellai Kondaikadalai',
  'black chickpeas': 'Karuppu Kondaikadalai',
  'karuppu kondaikadalai': 'Karuppu Kondaikadalai',
  'kidney beans': 'Rajma',
  'rajma': 'Rajma',
  'black-eyed peas': 'Kaaraamani',
  'kaaraamani': 'Kaaraamani',
  'karamani': 'Kaaraamani',
  'field beans': 'Mochai',
  'mochai': 'Mochai',
  'soybeans': 'Soya Beans',
  'soya beans': 'Soya Beans',
  'salt': 'Uppu',
  'uppu': 'Uppu',
  'sugar': 'Sarkarai',
  'sarkarai': 'Sarkarai',
  'jaggery': 'Vellam',
  'vellam': 'Vellam',
  'chilli': 'Milagai',
  'milagaai': 'Milagai',
  'chilli powder': 'Milagai Thool',
  'milagaai thool': 'Milagai Thool',
  'milagai thool': 'Milagai Thool',
  'black pepper': 'Milagu',
  'milagu': 'Milagu',
  'pepper powder': 'Milagu Thool',
  'milagu thool': 'Milagu Thool',
  'turmeric': 'Manjal',
  'manjal': 'Manjal',
  'turmeric powder': 'Manjal Thool',
  'manjal thool': 'Manjal Thool',
  'cumin': 'Seeragam',
  'seeragam': 'Seeragam',
  'coriander seeds': 'Dhaniya',
  'dhaniya': 'Dhaniya',
  'coriander powder': 'Dhaniya Thool',
  'dhaniya thool': 'Dhaniya Thool',
  'fennel seeds': 'Sombu',
  'sombu': 'Sombu',
  'fenugreek': 'Vendhayam',
  'vendhayam': 'Vendhayam',
  'mustard seeds': 'Kadugu',
  'kadugu': 'Kadugu',
  'fennel': 'Perunjeeragam',
  'perunjeeragam': 'Perunjeeragam',
  'ajwain / carom seeds': 'Omam',
  'omam': 'Omam',
  'cardamom': 'Yelakkai',
  'elakkai': 'Yelakkai',
  'yelakkai': 'Yelakkai',
  'cloves': 'Kiraambu',
  'kirambu': 'Kiraambu',
  'kiraambu': 'Kiraambu',
  'cinnamon': 'Pattai',
  'pattai': 'Pattai',
  'bay leaf': 'Biryani Ilai',
  'biryani ilai': 'Biryani Ilai',
  'star anise': 'Annaasi Poo',
  'annasipoo': 'Annaasi Poo',
  'nutmeg': 'Jaadhikkai',
  'jathikkai': 'Jaadhikkai',
  'mace': 'Jaadhipathiri',
  'jathipathiri': 'Jaadhipathiri',
  'poppy seeds': 'Kasakasa',
  'kasakasa': 'Kasakasa',
  'sesame seeds': 'Ellu',
  'ellu': 'Ellu',
  'asafoetida': 'Perungaayam',
  'perungayam': 'Perungaayam',
  'dried fenugreek leaves': 'Kasuri Methi',
  'kasuri methi': 'Kasuri Methi',
  'cooking oil': 'Samayal Ennai',
  'samayal ennai': 'Samayal Ennai',
  'sesame oil': 'Nallennai',
  'nallennai': 'Nallennai',
  'coconut oil': 'Thengai Ennai',
  'thengai ennai': 'Thengai Ennai',
  'groundnut oil': 'Kadalai Ennai',
  'kadalai ennai': 'Kadalai Ennai',
  'sunflower oil': 'Sooriyagaanthi Ennai',
  'suryakanthi ennai': 'Sooriyagaanthi Ennai',
  'olive oil': 'Olive Ennai',
  'olive ennai': 'Olive Ennai',
  'coconut milk': 'Thengai Paal',
  'thengai paal': 'Thengai Paal',
  'tomato sauce': 'Tomato Sauce',
  'thakkali sauce': 'Tomato Sauce',
  'soy sauce': 'Soya Sauce',
  'soya sauce': 'Soya Sauce',
  'vinegar': 'Vinegar',
  'pickle': 'Oorugai',
  'oorugai': 'Oorugai',
  'papad': 'Appalam',
  'appalam': 'Appalam',
  'vadam': 'Vadagam',
  'vadagam': 'Vadagam',
  'idli powder': 'Idli Podi',
  'idli podi': 'Idli Podi',
  'sambar powder': 'Sambar Podi',
  'sambar podi': 'Sambar Podi',
  'rasam powder': 'Rasappodi',
  'rasam podi': 'Rasappodi',
  'garam masala': 'Garam Masala',
  'biryani masala': 'Biryani Masala',

  // ── Dairy ────────────────────────────────────────────
  'milk': 'Paal',
  'paal': 'Paal',
  'curd / yogurt': 'Thayir',
  'curd': 'Thayir',
  'thayir': 'Thayir',
  'buttermilk': 'Moru',
  'mor': 'Moru',
  'moru': 'Moru',
  'butter': 'Vennai',
  'vennai': 'Vennai',
  'ghee': 'Nei',
  'nei': 'Nei',
  'paneer': 'Paneer',
  'cheese': 'Cheese',
  'cream': 'Cream',
  // Exact user specification: Tanglish: Kandenst Milk
  'condensed milk': 'Kandenst Milk',
  'condensed paal': 'Kandenst Milk',
  'milk powder': 'Paal Powder',
  'paal pavadar': 'Paal Powder',
  'paal powder': 'Paal Powder',

  // ── Nuts & Dry Fruits ────────────────────────────────
  'cashew': 'Mundhiri',
  'mundhiri': 'Mundhiri',
  'almond': 'Badam',
  'badam': 'Badam',
  'pistachio': 'Pista',
  'pista': 'Pista',
  'walnut': 'Walnut',
  'peanuts': 'Nilakkadalai',
  'nilakkadalai': 'Nilakkadalai',
  'raisins': 'Ular Dhraakshai (Kismis)',
  'ular dhraakshai': 'Ular Dhraakshai (Kismis)',
  'figs': 'Athippazham',
  'almonds (badam paruppu)': 'Badam Paruppu',
  'badam paruppu': 'Badam Paruppu',
  'pumpkin seeds': 'Poosani Vidhai',
  'poosani vidhai': 'Poosani Vidhai',
  'sunflower seeds': 'Sooriyagaanthi Vidhai',
  'sooriyagaanthi vidhai': 'Sooriyagaanthi Vidhai',
  'chia seeds': 'Chia Vidhai',
  'chia vidhai': 'Chia Vidhai',
  'flax seeds': 'Aali Vidhai',
  'aali vidhai': 'Aali Vidhai',
};

// Direct Tamil Script to Tanglish dictionary for 100% accuracy on all catalog items
export const TAMIL_TO_TANGLISH = {
  // Dairy
  'கண்டென்ஸ்டு மில்க்': 'Kandenst Milk',
  'பால்': 'Paal',
  'தயிர்': 'Thayir',
  'மோர்': 'Moru',
  'வெண்ணெய்': 'Vennai',
  'நெய்': 'Nei',
  'பன்னீர்': 'Paneer',
  'சீஸ்': 'Cheese',
  'கிரீம்': 'Cream',
  'பால் பவுடர்': 'Paal Powder',

  // Vegetables
  'தக்காளி': 'Thakkali',
  'உருளைக்கிழங்கு': 'Urulaikizhangu',
  'வெங்காயம்': 'Vengayam',
  'பூண்டு': 'Poondu',
  'இஞ்சி': 'Inji',
  'கேரட்': 'Carrot',
  'முட்டைக்கோஸ்': 'Muttaikose',
  'காலிஃபிளவர்': 'Cauliflower',
  'புரோக்கோலி': 'Broccoli',
  'கீரை': 'Keerai',
  'பட்டாணி': 'Pattani',
  'பீன்ஸ்': 'Beans',
  'வெண்டைக்காய்': 'Vendakkai',
  'கத்திரிக்காய்': 'Kathirikkai',
  'குடைமிளகாய்': 'Kudaimilagai',
  'பச்சை மிளகாய்': 'Pachai Milagai',
  'காய்ந்த மிளகாய்': 'Kaanja Milagai',
  'பாகற்காய்': 'Pavakkai',
  'சுரைக்காய்': 'Suraikkai',
  'பீர்க்கங்காய்': 'Peerkangai',
  'புடலங்காய்': 'Pudalangai',
  'பூசணிக்காய்': 'Poosanikkai',
  'மஞ்சள் பூசணி': 'Manjal Poosani',
  'சர்க்கரைவள்ளி கிழங்கு': 'Sakkaravalli Kizhangu',
  'சேனைக்கிழங்கு': 'Senaikizhangu',
  'சேப்பங்கிழங்கு': 'Seppankizhangu',
  'முள்ளங்கி': 'Mullangi',
  'பீட்ரூட்': 'Beetroot',
  'டர்னிப்': 'Turnip',
  'சோளம்': 'Cholam',
  'காளான்': 'Kaalan',
  'வெங்காயத்தாள்': 'Vengayathaal',
  'லீக்ஸ்': 'Leeks',
  'செலரி': 'Celery',
  'வெள்ளரிக்காய்': 'Vellarikkai',
  'சுக்கிணி': 'Zucchini',
  'முருங்கைக்காய்': 'Murungakkai',
  'வாழக்காய்': 'Vazhaikkai',
  'வாழைக்காய்': 'Vazhaikkai',
  'பப்பாளிக்காய்': 'Pappalikkai',
  'கொத்தவரங்காய்': 'Kothavarangai',
  'அவரைக்காய்': 'Avaraikkai',
  'வெந்தயக் கீரை': 'Vendhaya Keerai',
  'சின்ன வெங்காயம்': 'Chinna Vengayam',
  'சௌ சௌ': 'Chow Chow',
  'பிரெஞ்ச் பீன்ஸ்': 'French Beans',
  'பாலக்கீரை': 'Paalakeerai',
  'புதினா': 'Pudina',
  'கொத்தமல்லி': 'Kothamalli',
  'கறிவேப்பிலை': 'Kariveppilai',

  // Fruits
  'மாம்பழம்': 'Maambazham',
  'ஆப்பிள்': 'Aappil',
  'வாழைப்பழம்': 'Vazhaipazham',
  'திராட்சை': 'Dhraakshai',
  'ஆரஞ்சு': 'Aaranju',
  'பப்பாளி': 'Pappaali',
  'தர்பூசணி': 'Tharpoosani',
  'முலாம்பழம்': 'Mulaambazham',
  'அன்னாசி': 'Annaasi',
  'மாதுளை': 'Maadhulai',
  'கொய்யா': 'Koyyaa',
  'சப்போட்டா': 'Sapota',
  'தேங்காய்': 'Thengai',
  'எலுமிச்சை': 'Elumichai',
  'பச்சை எலுமிச்சை': 'Pachai Elumichai',
  'ஸ்ட்ராபெர்ரி': 'Strawberry',
  'கிவி': 'Kiwi',
  'பேரிக்காய்': 'Perikkaai',
  'பீச்': 'Peach',
  'பிளம்ஸ்': 'Plums',
  'செர்ரி': 'Cherry',
  'அத்திப்பழம்': 'Athippazham',
  'டிராகன் பழம்': 'Dragon Pazham',
  'வெண்ணெய் பழம்': 'Vennai Pazham',
  'பலாப்பழம்': 'Palaappazham',
  'சீதாப்பழம்': 'Seethaappazham',
  'விளிம்பிப் பழம்': 'Vilambi Pazham',
  'பாஷன் ஃப்ரூட்': 'Passion Fruit',
  'புளி': 'Puli',
  'நெல்லிக்காய்': 'Nellikkai',
  'பேரீச்சம்பழம்': 'Perichampazham',
  'லிச்சி': 'Litchi',

  // Groceries
  'அரிசி': 'Arisi',
  'புழுங்கல் அரிசி': 'Puzhungal Arisi',
  'பச்சரிசி': 'Pacharisi',
  'இட்லி அரிசி': 'Idli Arisi',
  'பாசுமதி அரிசி': 'Basmati Arisi',
  'கோதுமை': 'Godhumai',
  'கோதுமை மாவு': 'Godhumai Maavu',
  'மைதா': 'Maida',
  'ரவை': 'Ravai',
  'கம்பு': 'Kambu',
  'கேழ்வரகு': 'Kezhvaragu',
  'தினை': 'Thinai',
  'சாமை': 'Saamai',
  'வரகு': 'Varagu',
  'குதிரைவாலி': 'Kuthiraivaali',
  'ஓட்ஸ்': 'Oats',
  'அவல்': 'Aval',
  'சோள மாவு': 'Chola Maavu',
  'கடலை மாவு': 'Kadalai Maavu',
  'அரிசி மாவு': 'Arisi Maavu',
  'உளுந்து மாவு': 'Ulundhu Maavu',
  'துவரம் பருப்பு': 'Thuvaram Paruppu',
  'பாசிப்பருப்பு': 'Paasi Paruppu',
  'பாசிப்பயறு': 'Paasi Payaru',
  'உளுத்தம் பருப்பு': 'Ulutham Paruppu',
  'கடலைப் பருப்பு': 'Kadalai Paruppu',
  'கொள்ளு': 'Kollu',
  'மசூர் பருப்பு': 'Masoor Paruppu',
  'வெள்ளை கொண்டைக்கடலை': 'Vellai Kondaikadalai',
  'கருப்பு கொண்டைக்கடலை': 'Karuppu Kondaikadalai',
  'ராஜ்மா': 'Rajma',
  'காராமணி': 'Kaaraamani',
  'மொச்சை': 'Mochai',
  'சோயா பீன்ஸ்': 'Soya Beans',
  'உப்பு': 'Uppu',
  'சர்க்கரை': 'Sarkarai',
  'வெல்லம்': 'Vellam',
  'மிளகாய்': 'Milagai',
  'மிளகாய்த்தூள்': 'Milagai Thool',
  'மிளகு': 'Milagu',
  'மிளகுத்தூள்': 'Milagu Thool',
  'மஞ்சள்': 'Manjal',
  'மஞ்சள் தூள்': 'Manjal Thool',
  'சீரகம்': 'Seeragam',
  'தனியா': 'Dhaniya',
  'தனியாத்தூள்': 'Dhaniya Thool',
  'சோம்பு': 'Sombu',
  'வெந்தயம்': 'Vendhayam',
  'கடுகு': 'Kadugu',
  'பெருஞ்சீரகம்': 'Perunjeeragam',
  'ஓமம்': 'Omam',
  'ஏலக்காய்': 'Yelakkai',
  'கிராம்பு': 'Kiraambu',
  'பட்டை': 'Pattai',
  'பிரியாணி இலை': 'Biryani Ilai',
  'அன்னாசிப்பூ': 'Annaasi Poo',
  'ஜாதிக்காய்': 'Jaadhikkai',
  'ஜாதிபத்திரி': 'Jaadhipathiri',
  'கசகசா': 'Kasakasa',
  'எள்': 'Ellu',
  'பெருங்காயம்': 'Perungaayam',
  'கசூரி மேத்தி': 'Kasuri Methi',
  'சமையல் எண்ணெய்': 'Samayal Ennai',
  'நல்லெண்ணெய்': 'Nallennai',
  'தேங்காய் எண்ணெய்': 'Thengai Ennai',
  'கடலை எண்ணெய்': 'Kadalai Ennai',
  'சூரியகாந்தி எண்ணெய்': 'Sooriyagaanthi Ennai',
  'ஆலிவ் எண்ணெய்': 'Olive Ennai',
  'தேங்காய்ப்பால்': 'Thengai Paal',
  'தக்காளி சாஸ்': 'Tomato Sauce',
  'சோயா சாஸ்': 'Soya Sauce',
  'வினிகர்': 'Vinegar',
  'ஊறுகாய்': 'Oorugai',
  'அப்பளம்': 'Appalam',
  'வடகம்': 'Vadagam',
  'இட்லி பொடி': 'Idli Podi',
  'சாம்பார் பொடி': 'Sambar Podi',
  'ரசப்பொடி': 'Rasappodi',
  'கரம் மசாலா': 'Garam Masala',
  'பிரியாணி மசாலா': 'Biryani Masala',

  // Nuts & Dry Fruits
  'முந்திரி': 'Mundhiri',
  'பாதாம்': 'Badam',
  'பிஸ்தா': 'Pista',
  'வால்நட்': 'Walnut',
  'நிலக்கடலை': 'Nilakkadalai',
  'உலர் திராட்சை': 'Ular Dhraakshai (Kismis)',
  'பேரீச்சம்பழம்': 'Perichampazham',
  'பாதாம் பருப்பு': 'Badam Paruppu',
  'பூசணி விதை': 'Poosani Vidhai',
  'சூரியகாந்தி விதை': 'Sooriyagaanthi Vidhai',
  'சியா விதை': 'Chia Vidhai',
  'ஆளி விதை': 'Aali Vidhai',
};

// Tamil character to basic phonetic Tanglish transliterator fallback
const TAMIL_VOWELS = {
  'அ': 'a', 'ஆ': 'aa', 'இ': 'i', 'ஈ': 'ee', 'உ': 'u', 'ஊ': 'oo',
  'எ': 'e', 'ஏ': 'ae', 'ஐ': 'ai', 'ஒ': 'o', 'ஓ': 'oa', 'ஔ': 'au'
};

const TAMIL_CONSONANTS = {
  'க': 'k', 'ங': 'ng', 'ச': 's', 'ஞ': 'ny', 'ட': 't', 'ண': 'n',
  'த': 'th', 'ந': 'n', 'ப': 'p', 'ம': 'm', 'ய': 'y', 'ர': 'r',
  'ல': 'l', 'வ': 'v', 'ழ': 'zh', 'ள': 'l', 'ற': 'r', 'ன': 'n',
  'ஜ': 'j', 'ஷ': 'sh', 'ஸ': 's', 'ஹ': 'h'
};

const TAMIL_DIACRITICS = {
  'ா': 'aa', 'ி': 'i', 'ீ': 'ee', 'ு': 'u', 'ூ': 'oo',
  'ெ': 'e', 'ே': 'ae', 'ை': 'ai', 'ொ': 'o', 'ோ': 'oa', 'ௌ': 'au',
  '்': '' // Pulli / virama: cancels implicit 'a'
};

/**
 * Phonetic transliteration from Tamil Unicode text into clean Tanglish.
 */
export function transliterateTamilToTanglish(text) {
  if (!text) return '';
  let result = '';
  const len = text.length;

  for (let i = 0; i < len; i++) {
    const ch = text[i];

    if (TAMIL_VOWELS[ch]) {
      result += TAMIL_VOWELS[ch];
    } else if (TAMIL_CONSONANTS[ch]) {
      const base = TAMIL_CONSONANTS[ch];
      const next = i + 1 < len ? text[i + 1] : null;

      if (next && next === '்') {
        result += base;
        i++; // skip pulli
      } else if (next && TAMIL_DIACRITICS[next] !== undefined) {
        result += base + TAMIL_DIACRITICS[next];
        i++; // skip diacritic
      } else {
        result += base + 'a';
      }
    } else {
      result += ch;
    }
  }

  // Capitalize words
  return result
    .split(' ')
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

/**
 * Returns the Tanglish (Tamil in English letters) representation for an item.
 * Always guaranteed to return a valid, clean Tanglish name for any item.
 * e.g.,
 * Tomato         -> "Thakkali"
 * Condensed Milk -> "Kandenst Milk"
 * Condensed Paal -> "Kandenst Milk"
 * Milk           -> "Paal"
 */
export function getTanglishName(item) {
  if (!item) return '';

  // 1. Direct item attribute if explicitly set
  if (item.name_tanglish && item.name_tanglish.trim()) {
    return item.name_tanglish.trim();
  }

  const cleanEn = (item.name || '').toLowerCase().trim();
  const cleanTa = (item.name_ta || '').trim();

  // 2. Direct Tamil script dictionary lookup (exact match)
  if (cleanTa && TAMIL_TO_TANGLISH[cleanTa]) {
    return TAMIL_TO_TANGLISH[cleanTa];
  }

  // 3. Exact dictionary lookup by English or Tanglish name
  if (cleanEn && TANGLISH_DICTIONARY[cleanEn]) {
    return TANGLISH_DICTIONARY[cleanEn];
  }

  // 4. Substring / partial key lookup in English dictionary
  if (cleanEn) {
    for (const [key, val] of Object.entries(TANGLISH_DICTIONARY)) {
      if (cleanEn === key || cleanEn.startsWith(key) || key.startsWith(cleanEn)) {
        return val;
      }
    }
  }

  // 5. Partial Tamil script lookup
  if (cleanTa) {
    for (const [key, val] of Object.entries(TAMIL_TO_TANGLISH)) {
      if (cleanTa.includes(key) || key.includes(cleanTa)) {
        return val;
      }
    }
  }

  // 6. Phonetic transliteration from Tamil script fallback
  if (cleanTa) {
    const transliterated = transliterateTamilToTanglish(cleanTa);
    if (transliterated) return transliterated;
  }

  // 7. Fallback: if name is non-empty, use name
  if (item.name && item.name.trim()) {
    return item.name.trim();
  }

  return '';
}

/**
 * ENGLISH_DICTIONARY — Mapping from Tanglish & Tamil script names to standard English words
 */
export const ENGLISH_DICTIONARY = {
  // ── Nuts & Dry Fruits ───────────────────────────────
  'badam': 'Almond',
  'badam paruppu': 'Almond',
  'almond': 'Almond',
  'almonds': 'Almond',
  'almonds (badam paruppu)': 'Almond',
  'mundhiri': 'Cashew',
  'cashew': 'Cashew',
  'cashews': 'Cashew',
  'pista': 'Pistachio',
  'pistachio': 'Pistachio',
  'pistachios': 'Pistachio',
  'walnut': 'Walnut',
  'walnuts': 'Walnut',
  'nilakkadalai': 'Peanuts',
  'peanut': 'Peanuts',
  'peanuts': 'Peanuts',
  'ular thiratchai': 'Raisins',
  'raisins': 'Raisins',
  'pericham pazham': 'Dates',
  'dates': 'Dates',
  'athi pazham': 'Figs',
  'figs': 'Figs',
  'poosani vidhai': 'Pumpkin Seeds',
  'pumpkin seeds': 'Pumpkin Seeds',
  'suryakanthi vidhai': 'Sunflower Seeds',
  'sunflower seeds': 'Sunflower Seeds',
  'chia vidhai': 'Chia Seeds',
  'chia seeds': 'Chia Seeds',
  'aali vidhai': 'Flax Seeds',
  'flax seeds': 'Flax Seeds',

  // ── Vegetables ──────────────────────────────────────
  'thakkali': 'Tomato',
  'tomato': 'Tomato',
  'urulaikizhangu': 'Potato',
  'potato': 'Potato',
  'vengayam': 'Onion',
  'onion': 'Onion',
  'chinna vengayam': 'Small Onion',
  'shallots': 'Small Onion',
  'poondu': 'Garlic',
  'garlic': 'Garlic',
  'inji': 'Ginger',
  'ginger': 'Ginger',
  'carrot': 'Carrot',
  'muttaikose': 'Cabbage',
  'cabbage': 'Cabbage',
  'cauliflower': 'Cauliflower',
  'broccoli': 'Broccoli',
  'keerai': 'Spinach',
  'spinach': 'Spinach',
  'palak': 'Palak Spinach',
  'palak keerai': 'Palak Spinach',
  'vendhaya keerai': 'Fenugreek Leaves',
  'pattani': 'Peas',
  'peas': 'Peas',
  'beans': 'Beans',
  'french beans': 'French Beans',
  'vendakkai': "Lady's Finger",
  'vendaikkai': "Lady's Finger",
  'lady finger': "Lady's Finger",
  'okra': "Lady's Finger",
  'kathirikkai': 'Brinjal',
  'brinjal': 'Brinjal',
  'eggplant': 'Brinjal',
  'kudaimilagai': 'Capsicum',
  'kudai milagaai': 'Capsicum',
  'capsicum': 'Capsicum',
  'pachai milagai': 'Green Chilli',
  'pachai milagaai': 'Green Chilli',
  'green chilli': 'Green Chilli',
  'kaanja milagai': 'Dry Red Chilli',
  'kaindha milagaai': 'Dry Red Chilli',
  'red chilli': 'Dry Red Chilli',
  'dry red chilli': 'Dry Red Chilli',
  'pavakkai': 'Bitter Gourd',
  'paavakkai': 'Bitter Gourd',
  'bitter gourd': 'Bitter Gourd',
  'suraikkai': 'Bottle Gourd',
  'sorakkai': 'Bottle Gourd',
  'bottle gourd': 'Bottle Gourd',
  'peerkangai': 'Ridge Gourd',
  'peerkkangkai': 'Ridge Gourd',
  'ridge gourd': 'Ridge Gourd',
  'pudalangai': 'Snake Gourd',
  'pudalangkai': 'Snake Gourd',
  'snake gourd': 'Snake Gourd',
  'poosanikkai': 'Ash Gourd',
  'ash gourd': 'Ash Gourd',
  'manjal poosani': 'Pumpkin',
  'pumpkin': 'Pumpkin',
  'sakkaravalli kizhangu': 'Sweet Potato',
  'sarkkaravalli': 'Sweet Potato',
  'sweet potato': 'Sweet Potato',
  'senaikizhangu': 'Yam',
  'senaikizhungu': 'Yam',
  'yam': 'Yam',
  'seppankizhangu': 'Colocasia',
  'cheppankizhungu': 'Colocasia',
  'colocasia': 'Colocasia',
  'mullangi': 'Radish',
  'radish': 'Radish',
  'beetroot': 'Beetroot',
  'turnip': 'Turnip',
  'cholam': 'Corn',
  'corn': 'Corn',
  'kaalan': 'Mushroom',
  'kaalaan': 'Mushroom',
  'mushroom': 'Mushroom',
  'vengayathaal': 'Spring Onion',
  'vengayathal': 'Spring Onion',
  'spring onion': 'Spring Onion',
  'leek': 'Leek',
  'leeks': 'Leek',
  'celery': 'Celery',
  'vellarikkai': 'Cucumber',
  'vellarikai': 'Cucumber',
  'cucumber': 'Cucumber',
  'zucchini': 'Zucchini',
  'murungakkai': 'Drumstick',
  'drumstick': 'Drumstick',
  'vazhaikkai': 'Raw Banana',
  'vazhakkai': 'Raw Banana',
  'raw banana': 'Raw Banana',
  'pappalikkai': 'Raw Papaya',
  'raw papaya': 'Raw Papaya',
  'kothavarangai': 'Cluster Beans',
  'kothavarankkai': 'Cluster Beans',
  'cluster beans': 'Cluster Beans',
  'avarakkai': 'Broad Beans',
  'broad beans': 'Broad Beans',
  'chow chow': 'Chayote',
  'chayote': 'Chayote',
  'pudina': 'Mint Leaves',
  'mint': 'Mint Leaves',
  'kothamalli': 'Coriander Leaves',
  'coriander': 'Coriander Leaves',

  // ── Fruits ──────────────────────────────────────────
  'maambazham': 'Mango',
  'mambazham': 'Mango',
  'mango': 'Mango',
  'apple': 'Apple',
  'vazhapazham': 'Banana',
  'vazhaipazham': 'Banana',
  'banana': 'Banana',
  'thiratchai': 'Grapes',
  'drakshai': 'Grapes',
  'grapes': 'Grapes',
  'aranju': 'Orange',
  'aaranju': 'Orange',
  'orange': 'Orange',
  'pappali': 'Papaya',
  'papaya': 'Papaya',
  'dharpoosani': 'Watermelon',
  'tarpoosani': 'Watermelon',
  'watermelon': 'Watermelon',
  'mulampazham': 'Muskmelon',
  'muskmelon': 'Muskmelon',
  'annasi': 'Pineapple',
  'annasipazham': 'Pineapple',
  'pineapple': 'Pineapple',
  'koyya': 'Guava',
  'guava': 'Guava',
  'madhulai': 'Pomegranate',
  'pomegranate': 'Pomegranate',
  'sapota': 'Sapota',
  'seethapazham': 'Custard Apple',
  'custard apple': 'Custard Apple',
  'elamichai': 'Lemon',
  'lemon': 'Lemon',
  'sathukudi': 'Sweet Lime',
  'sweet lime': 'Sweet Lime',
  'nellikai': 'Gooseberry',
  'amla': 'Gooseberry',
  'gooseberry': 'Gooseberry',
  'kiwi': 'Kiwi',
  'strawberry': 'Strawberry',
  'blueberry': 'Blueberry',
  'avocado': 'Avocado',
  'dragon fruit': 'Dragon Fruit',
  'plum': 'Plum',
  'pear': 'Pear',
  'peach': 'Peach',
  'cherry': 'Cherry',
  'lychee': 'Lychee',

  // ── Dairy ───────────────────────────────────────────
  'paal': 'Milk',
  'milk': 'Milk',
  'thayir': 'Curd',
  'curd': 'Curd',
  'yogurt': 'Curd',
  'mor': 'Buttermilk',
  'buttermilk': 'Buttermilk',
  'vennai': 'Butter',
  'butter': 'Butter',
  'nei': 'Ghee',
  'ghee': 'Ghee',
  'paneer': 'Paneer',
  'cheese': 'Cheese',
  'cream': 'Cream',
  'kandenst milk': 'Condensed Milk',
  'condensed milk': 'Condensed Milk',
  'paal powder': 'Milk Powder',
  'milk powder': 'Milk Powder',

  // ── Groceries ───────────────────────────────────────
  'vendhayam': 'Fenugreek',
  'fenugreek': 'Fenugreek',
  'kadugu': 'Mustard',
  'mustard': 'Mustard',
  'perunjeeragam': 'Fennel Seeds',
  'sombu': 'Fennel Seeds',
  'fennel': 'Fennel Seeds',
  'seeragam': 'Cumin Seeds',
  'jeera': 'Cumin Seeds',
  'cumin': 'Cumin Seeds',
  'milagu': 'Black Pepper',
  'pepper': 'Black Pepper',
  'omam': 'Carom Seeds',
  'carom': 'Carom Seeds',
  'elakkai': 'Cardamom',
  'cardamom': 'Cardamom',
  'kirambu': 'Cloves',
  'lavangam': 'Cloves',
  'cloves': 'Cloves',
  'pattai': 'Cinnamon',
  'cinnamon': 'Cinnamon',
  'biryani ilai': 'Bay Leaf',
  'bay leaf': 'Bay Leaf',
  'annasipoo': 'Star Anise',
  'star anise': 'Star Anise',
  'jathikkai': 'Nutmeg',
  'nutmeg': 'Nutmeg',
  'jathipathiri': 'Mace',
  'mace': 'Mace',
  'kasakasa': 'Poppy Seeds',
  'poppy seeds': 'Poppy Seeds',
  'ellu': 'Sesame Seeds',
  'sesame seeds': 'Sesame Seeds',
  'perungayam': 'Asafoetida',
  'asafoetida': 'Asafoetida',
  'hing': 'Asafoetida',
  'karuveppilai': 'Curry Leaves',
  'curry leaves': 'Curry Leaves',
  'kasuri methi': 'Kasuri Methi',
  'samayal ennai': 'Cooking Oil',
  'cooking oil': 'Cooking Oil',
  'nallennai': 'Sesame Oil',
  'sesame oil': 'Sesame Oil',
  'thengai ennai': 'Coconut Oil',
  'coconut oil': 'Coconut Oil',
  'kadalai ennai': 'Groundnut Oil',
  'groundnut oil': 'Groundnut Oil',
  'suryakanthi ennai': 'Sunflower Oil',
  'sunflower oil': 'Sunflower Oil',
  'olive ennai': 'Olive Oil',
  'olive oil': 'Olive Oil',
  'thengai': 'Coconut',
  'coconut': 'Coconut',
  'thengai paal': 'Coconut Milk',
  'coconut milk': 'Coconut Milk',
  'puli': 'Tamarind',
  'tamarind': 'Tamarind',
  'thakkali sauce': 'Tomato Sauce',
  'tomato sauce': 'Tomato Sauce',
  'soya sauce': 'Soya Sauce',
  'vinegar': 'Vinegar',
  'oorugai': 'Pickle',
  'pickle': 'Pickle',
  'appalam': 'Papad',
  'papad': 'Papad',
  'vadagam': 'Crisps',
  'arisi': 'Rice',
  'rice': 'Rice',
  'ulundhu': 'Urad Dal',
  'urad dal': 'Urad Dal',
  'thuvaram paruppu': 'Toor Dal',
  'toor dal': 'Toor Dal',
  'pasi paruppu': 'Moong Dal',
  'moong dal': 'Moong Dal',
  'kadalai paruppu': 'Chana Dal',
  'chana dal': 'Chana Dal',
  'kothumai maavu': 'Wheat Flour',
  'wheat flour': 'Wheat Flour',
  'atta': 'Wheat Flour',
  'maida': 'All Purpose Flour',
  'rava': 'Semolina',
  'semolina': 'Semolina',
  'sooji': 'Semolina',
  'semiya': 'Vermicelli',
  'vermicelli': 'Vermicelli',
  'aval': 'Flattened Rice',
  'poha': 'Flattened Rice',
  'sakkarai': 'Sugar',
  'sugar': 'Sugar',
  'vellam': 'Jaggery',
  'jaggery': 'Jaggery',
  'naatu sakkarai': 'Brown Sugar',
  'kalkandu': 'Rock Sugar',
  'uppu': 'Salt',
  'salt': 'Salt',
  'kal uppu': 'Rock Salt',
  'rock salt': 'Rock Salt',
  'milagai podi': 'Chilli Powder',
  'chilli powder': 'Chilli Powder',
  'malli podi': 'Coriander Powder',
  'coriander powder': 'Coriander Powder',
  'manjal podi': 'Turmeric Powder',
  'turmeric powder': 'Turmeric Powder',
  'seeraga podi': 'Cumin Powder',
  'cumin powder': 'Cumin Powder',
  'milagu podi': 'Pepper Powder',
  'pepper powder': 'Pepper Powder',
  'sambar podi': 'Sambar Powder',
  'sambar powder': 'Sambar Powder',
  'rasam podi': 'Rasam Powder',
  'rasam powder': 'Rasam Powder',
  'idli podi': 'Idli Podi',
  'garam masala': 'Garam Masala',
  'biryani masala': 'Biryani Masala',

  // ── Tamil Script Direct Mappings ───────────────────
  'பாதாம்': 'Almond',
  'பாதாம் பருப்பு': 'Almond',
  'முந்திரி': 'Cashew',
  'பிஸ்தா': 'Pistachio',
  'வால்நட்': 'Walnut',
  'நிலக்கடலை': 'Peanuts',
  'உலர் திராட்சை': 'Raisins',
  'பேரீச்சம்பழம்': 'Dates',
  'அத்திப்பழம்': 'Figs',
  'பூசணி விதை': 'Pumpkin Seeds',
  'சூரியகாந்தி விதை': 'Sunflower Seeds',
  'சியா விதை': 'Chia Seeds',
  'ஆளி விதை': 'Flax Seeds',
  'தக்காளி': 'Tomato',
  'உருளைக்கிழங்கு': 'Potato',
  'வெங்காயம்': 'Onion',
  'சின்ன வெங்காயம்': 'Small Onion',
  'பூண்டு': 'Garlic',
  'இஞ்சி': 'Ginger',
  'கேரட்': 'Carrot',
  'முட்டைக்கோஸ்': 'Cabbage',
  'காலிஃபிளவர்': 'Cauliflower',
  'புரோக்கோலி': 'Broccoli',
  'கீரை': 'Spinach',
  'பாலக்கீரை': 'Palak Spinach',
  'வெந்தயக் கீரை': 'Fenugreek Leaves',
  'பட்டாணி': 'Peas',
  'பீன்ஸ்': 'Beans',
  'பிரெஞ்ச் பீன்ஸ்': 'French Beans',
  'வெண்டைக்காய்': "Lady's Finger",
  'கத்திரிக்காய்': 'Brinjal',
  'குடைமிளகாய்': 'Capsicum',
  'பச்சை மிளகாய்': 'Green Chilli',
  'காய்ந்த மிளகாய்': 'Dry Red Chilli',
  'பாகற்காய்': 'Bitter Gourd',
  'சுரைக்காய்': 'Bottle Gourd',
  'பீர்க்கங்காய்': 'Ridge Gourd',
  'புடலங்காய்': 'Snake Gourd',
  'பூசணிக்காய்': 'Ash Gourd',
  'மஞ்சள் பூசணி': 'Pumpkin',
  'சர்க்கரைவள்ளி கிழங்கு': 'Sweet Potato',
  'சேனைக்கிழங்கு': 'Yam',
  'சேப்பங்கிழங்கு': 'Colocasia',
  'முள்ளங்கி': 'Radish',
  'பீட்ரூட்': 'Beetroot',
  'டர்னிப்': 'Turnip',
  'சோளம்': 'Corn',
  'காளான்': 'Mushroom',
  'வெங்காயத்தாள்': 'Spring Onion',
  'லீக்ஸ்': 'Leek',
  'செலரி': 'Celery',
  'வெள்ளரிக்காய்': 'Cucumber',
  'சுக்கிணி': 'Zucchini',
  'முருங்கைக்காய்': 'Drumstick',
  'வாழக்காய்': 'Raw Banana',
  'பப்பாளிக்காய்': 'Raw Papaya',
  'கொத்தவரங்காய்': 'Cluster Beans',
  'அவரைக்காய்': 'Broad Beans',
  'சௌ சௌ': 'Chayote',
  'புதினா': 'Mint Leaves',
  'கொத்தமல்லி': 'Coriander Leaves',
  'மாம்பழம்': 'Mango',
  'ஆப்பிள்': 'Apple',
  'வாழைப்பழம்': 'Banana',
  'திராட்சை': 'Grapes',
  'ஆரஞ்சு': 'Orange',
  'பப்பாளி': 'Papaya',
  'தர்பூசணி': 'Watermelon',
  'முலாம்பழம்': 'Muskmelon',
  'அன்னாசி': 'Pineapple',
  'கொய்யா': 'Guava',
  'மாதுளை': 'Pomegranate',
  'சப்போட்டா': 'Sapota',
  'சீத்தாப்பழம்': 'Custard Apple',
  'எலுமிச்சை': 'Lemon',
  'சாத்துக்குடி': 'Sweet Lime',
  'நெல்லிக்காய்': 'Gooseberry',
  'பால்': 'Milk',
  'தயிர்': 'Curd',
  'மோர்': 'Buttermilk',
  'வெண்ணெய்': 'Butter',
  'நெய்': 'Ghee',
  'பன்னீர்': 'Paneer',
  'சீஸ்': 'Cheese',
  'கிரீம்': 'Cream',
  'கண்டென்ஸ்டு மில்க்': 'Condensed Milk',
  'பால் பவுடர்': 'Milk Powder',
  'வெந்தயம்': 'Fenugreek',
  'கடுகு': 'Mustard',
  'பெருஞ்சீரகம்': 'Fennel Seeds',
  'சீரகம்': 'Cumin Seeds',
  'மிளகு': 'Black Pepper',
  'ஓமம்': 'Carom Seeds',
  'ஏலக்காய்': 'Cardamom',
  'கிராம்பு': 'Cloves',
  'பட்டை': 'Cinnamon',
  'பிரியாணி இலை': 'Bay Leaf',
  'அன்னாசிப்பூ': 'Star Anise',
  'ஜாதிக்காய்': 'Nutmeg',
  'ஜாதிபத்திரி': 'Mace',
  'கசகசா': 'Poppy Seeds',
  'எள்': 'Sesame Seeds',
  'பெருங்காயம்': 'Asafoetida',
  'கறிவேப்பிலை': 'Curry Leaves',
  'கசூரி மேத்தி': 'Kasuri Methi',
  'சமையல் எண்ணெய்': 'Cooking Oil',
  'நல்லெண்ணெய்': 'Sesame Oil',
  'தேங்காய் எண்ணெய்': 'Coconut Oil',
  'கடலை எண்ணெய்': 'Groundnut Oil',
  'சூரியகாந்தி எண்ணெய்': 'Sunflower Oil',
  'ஆலிவ் எண்ணெய்': 'Olive Oil',
  'தேங்காய்': 'Coconut',
  'தேங்காய்ப்பால்': 'Coconut Milk',
  'புளி': 'Tamarind',
  'தக்காளி சாஸ்': 'Tomato Sauce',
  'சோயா சாஸ்': 'Soya Sauce',
  'வினிகர்': 'Vinegar',
  'ஊறுகாய்': 'Pickle',
  'அப்பளம்': 'Papad',
  'வடகம்': 'Crisps',
  'அரிசி': 'Rice',
  'உளுந்து': 'Urad Dal',
  'துவரம் பருப்பு': 'Toor Dal',
  'பாசிப் பருப்பு': 'Moong Dal',
  'கடலைப் பருப்பு': 'Chana Dal',
  'கோதுமை மாவு': 'Wheat Flour',
  'மைதா': 'All Purpose Flour',
  'ரவா': 'Semolina',
  'சேமியா': 'Vermicelli',
  'அவல்': 'Flattened Rice',
  'சர்க்கரை': 'Sugar',
  'வெல்லம்': 'Jaggery',
  'நாட்டுச் சர்க்கரை': 'Brown Sugar',
  'கற்கண்டு': 'Rock Sugar',
  'உப்பு': 'Salt',
  'கல் உப்பு': 'Rock Salt',
  'மிளகாய் பொடி': 'Chilli Powder',
  'மல்லி பொடி': 'Coriander Powder',
  'மஞ்சள் பொடி': 'Turmeric Powder',
  'சீரகப் பொடி': 'Cumin Powder',
  'மிளகுப் பொடி': 'Pepper Powder',
  'சாம்பார் பொடி': 'Sambar Powder',
  'ரசப்பொடி': 'Rasam Powder',
  'இட்லி பொடி': 'Idli Podi',
  'கரம் மசாலா': 'Garam Masala',
  'பிரியாணி மசாலா': 'Biryani Masala',
};

/**
 * Returns the proper English word/name for any catalog item.
 * e.g.,
 * Badam          -> "Almond"
 * Thakkali       -> "Tomato"
 * Urulaikizhangu -> "Potato"
 * Vengayam       -> "Onion"
 * Apple          -> "Apple"
 * Condensed Milk -> "Condensed Milk"
 */
export function getEnglishName(item) {
  if (!item) return '';

  // 1. Direct explicit english attribute
  if (item.name_en && item.name_en.trim()) {
    return item.name_en.trim();
  }

  const cleanEn = (item.name || '').toLowerCase().trim();
  const cleanTa = (item.name_ta || '').trim();

  // 2. Direct Tamil script dictionary lookup (exact match)
  if (cleanTa && ENGLISH_DICTIONARY[cleanTa]) {
    return ENGLISH_DICTIONARY[cleanTa];
  }

  // 3. Exact dictionary lookup by name
  if (cleanEn && ENGLISH_DICTIONARY[cleanEn]) {
    return ENGLISH_DICTIONARY[cleanEn];
  }

  // 4. Substring / partial key lookup in English dictionary
  if (cleanEn) {
    for (const [key, val] of Object.entries(ENGLISH_DICTIONARY)) {
      if (cleanEn === key || cleanEn.startsWith(key) || key.startsWith(cleanEn)) {
        return val;
      }
    }
  }

  // 5. Partial Tamil script lookup
  if (cleanTa) {
    for (const [key, val] of Object.entries(ENGLISH_DICTIONARY)) {
      if (cleanTa.includes(key) || key.includes(cleanTa)) {
        return val;
      }
    }
  }

  // 6. Fallback: if name is non-empty, use name
  if (item.name && item.name.trim()) {
    return item.name.trim();
  }

  return '';
}
