INSERT INTO items (name, name_ta, category, price_per_kg, emoji) VALUES
  ('Tomato',            'தக்காளி',            'vegetable', 30.00,  '🍅'),
  ('Potato',            'உருளைக்கிழங்கு',      'vegetable', 25.00,  '🥔'),
  ('Onion',             'வெங்காயம்',          'vegetable', 35.00,  '🧅'),
  ('Garlic',            'பூண்டு',              'vegetable', 120.00, '🧄'),
  ('Ginger',            'இஞ்சி',              'vegetable', 80.00,  '🫚'),
  ('Carrot',            'கேரட்',              'vegetable', 40.00,  '🥕'),
  ('Cabbage',           'முட்டைக்கோஸ்',       'vegetable', 20.00,  '🥬'),
  ('Cauliflower',       'காலிஃபிளவர்',       'vegetable', 30.00,  '🥦'),
  ('Broccoli',          'புரோக்கோலி',         'vegetable', 60.00,  '🥦'),
  ('Spinach',           'கீரை',               'vegetable', 30.00,  '🌿'),
  ('Peas',              'பட்டாணி',            'vegetable', 60.00,  '🫛'),
  ('Beans',             'பீன்ஸ்',              'vegetable', 50.00,  '🫘'),
  ('Lady Finger (Okra)','வெண்டைக்காய்',        'vegetable', 40.00,  '🌾'),
  ('Brinjal (Eggplant)','கத்திரிக்காய்',       'vegetable', 25.00,  '🍆'),
  ('Capsicum',          'குடைமிளகாய்',        'vegetable', 60.00,  '🫑'),
  ('Green Chilli',      'பச்சை மிளகாய்',       'vegetable', 50.00,  '🌶️'),
  ('Red Chilli',        'காய்ந்த மிளகாய்',     'vegetable', 200.00, '🌶️'),
  ('Bitter Gourd',      'பாகற்காய்',          'vegetable', 40.00,  '🥒'),
  ('Bottle Gourd',      'சுரைக்காய்',          'vegetable', 20.00,  '🥒'),
  ('Ridge Gourd',       'பீர்க்கங்காய்',        'vegetable', 30.00,  '🥒'),
  ('Snake Gourd',       'புடலங்காய்',          'vegetable', 25.00,  '🥒'),
  ('Ash Gourd',         'பூசணிக்காய்',         'vegetable', 15.00,  '🥒'),
  ('Pumpkin',           'மஞ்சள் பூசணி',       'vegetable', 20.00,  '🎃'),
  ('Sweet Potato',      'சர்க்கரைவள்ளி கிழங்கு', 'vegetable', 35.00,  '🍠'),
  ('Yam',               'சேனைக்கிழங்கு',       'vegetable', 40.00,  '🌱'),
  ('Colocasia (Taro)',  'சேப்பங்கிழங்கு',      'vegetable', 30.00,  '🌱'),
  ('Radish',            'முள்ளங்கி',           'vegetable', 20.00,  '🌱'),
  ('Beetroot',          'பீட்ரூட்',            'vegetable', 30.00,  '🟣'),
  ('Turnip',            'டர்னிப்',            'vegetable', 25.00,  '🌱'),
  ('Corn',              'சோளம்',              'vegetable', 20.00,  '🌽'),
  ('Mushroom',          'காளான்',             'vegetable', 150.00, '🍄'),
  ('Spring Onion',      'வெங்காயத்தாள்',      'vegetable', 30.00,  '🧅'),
  ('Leek',              'லீக்ஸ்',              'vegetable', 40.00,  '🌿'),
  ('Celery',            'செலரி',              'vegetable', 60.00,  '🌿'),
  ('Cucumber',          'வெள்ளரிக்காய்',        'vegetable', 20.00,  '🥒'),
  ('Zucchini',          'சுக்கிணி',            'vegetable', 50.00,  '🥒'),
  ('Drumstick',         'முருங்கைக்காய்',        'vegetable', 60.00,  '🌿'),
  ('Raw Banana',        'வாழக்காய்',          'vegetable', 30.00,  '🍌'),
  ('Raw Papaya',        'பப்பாளிக்காய்',        'vegetable', 25.00,  '🌱'),
  ('Cluster Beans',     'கொத்தவரங்காய்',      'vegetable', 50.00,  '🫘'),
  ('Flat Beans',        'அவரைக்காய்',          'vegetable', 45.00,  '🫘'),
  ('Fenugreek Leaves',  'வெந்தயக் கீரை',       'vegetable', 20.00,  '🌿');

INSERT INTO items (name, name_ta, category, price_per_kg, emoji) VALUES
  ('Mango',          'மாம்பழம்',         'fruit', 80.00,  '🥭'),
  ('Apple',          'ஆப்பிள்',           'fruit', 150.00, '🍎'),
  ('Banana',         'வாழைப்பழம்',       'fruit', 40.00,  '🍌'),
  ('Grapes',         'திராட்சை',          'fruit', 80.00,  '🍇'),
  ('Orange',         'ஆரஞ்சு',           'fruit', 60.00,  '🍊'),
  ('Papaya',         'பப்பாளி',          'fruit', 35.00,  '🫐'),
  ('Watermelon',     'தர்பூசணி',          'fruit', 20.00,  '🍉'),
  ('Muskmelon',      'முலாம்பழம்',        'fruit', 30.00,  '🍈'),
  ('Pineapple',      'அன்னாசி',          'fruit', 50.00,  '🍍'),
  ('Pomegranate',    'மாதுளை',           'fruit', 120.00, '🍎'),
  ('Guava',          'கொய்யா',           'fruit', 50.00,  '🍐'),
  ('Sapota (Chikoo)','சப்போட்டா',        'fruit', 60.00,  '🟤'),
  ('Coconut',        'தேங்காய்',          'fruit', 30.00,  '🥥'),
  ('Lemon',          'எலுமிச்சை',        'fruit', 80.00,  '🍋'),
  ('Lime',           'பச்சை எலுமிச்சை',   'fruit', 60.00,  '🟢'),
  ('Strawberry',     'ஸ்ட்ராபெர்ரி',     'fruit', 200.00, '🍓'),
  ('Kiwi',           'கிவி',              'fruit', 250.00, '🥝'),
  ('Pear',           'பேரிக்காய்',        'fruit', 100.00, '🍐'),
  ('Peach',          'பீச்',              'fruit', 150.00, '🍑'),
  ('Plum',           'பிளம்ஸ்',           'fruit', 120.00, '🟣'),
  ('Cherry',         'செர்ரி',            'fruit', 300.00, '🍒'),
  ('Fig',            'அத்திப்பழம்',       'fruit', 200.00, '🟤'),
  ('Dragon Fruit',   'டிராகன் பழம்',      'fruit', 200.00, '🐉'),
  ('Avocado',        'வெண்ணெய் பழம்',     'fruit', 250.00, '🥑'),
  ('Jackfruit',      'பலாப்பழம்',        'fruit', 40.00,  '🍈'),
  ('Custard Apple',  'சீதாப்பழம்',       'fruit', 80.00,  '🍏'),
  ('Star Fruit',     'விளிம்பிப் பழம்',    'fruit', 60.00,  '⭐'),
  ('Passion Fruit',  'பாஷன் ஃப்ரூட்',    'fruit', 150.00, '🟡'),
  ('Tamarind',       'புளி',              'fruit', 100.00, '🟤'),
  ('Amla (Gooseberry)', 'நெல்லிக்காய்',   'fruit', 60.00,  '🟢'),
  ('Dates',          'பேரீச்சம்பழம்',     'fruit', 200.00, '🟤'),
  ('Litchi',         'லிச்சி',            'fruit', 120.00, '🔴');
