INSERT INTO items (name, name_ta, category, price_per_kg, emoji) VALUES
  ('Tomato',            'தக்காளி',            'vegetable', 30.00,  '🍅'),
  ('Potato',            'உருளைக்கிழங்கு',      'vegetable', 25.00,  '🥔'),
  ('Onion',             'வெங்காயம்',          'vegetable', 35.00,  '🧅'),
  ('Garlic',            'பூண்டு',              'vegetable', 120.00, '🧄'),
  ('Ginger',            'இஞ்சி',              'vegetable', 80.00,  '🫚'),
  ('Carrot',            'கேரட்',              'vegetable', 40.00,  '🥕'),
  ('Cabbage',           'முட்டைக்கோஸ்',       'vegetable', 20.00,  '🥬'),
  ('Cauliflower',       'காலிஃபிளவர்',       'vegetable', 30.00,  '🥦'),
  ('Broccoli',          'புரோக்கோலி',         'vegetable', 60.00,  '🥦'),
  ('Spinach',           'கீரை',               'vegetable', 30.00,  '🌿'),
  ('Peas',              'பட்டாணி',            'vegetable', 60.00,  '🫛'),
  ('Beans',             'பீன்ஸ்',              'vegetable', 50.00,  '🫘'),
  ('Lady Finger (Okra)','வெண்டைக்காய்',        'vegetable', 40.00,  '🌾'),
  ('Brinjal (Eggplant)','கத்திரிக்காய்',       'vegetable', 25.00,  '🍆'),
  ('Capsicum',          'குடைமிளகாய்',        'vegetable', 60.00,  '🫑'),
  ('Green Chilli',      'பச்சை மிளகாய்',       'vegetable', 50.00,  '🌶️'),
  ('Red Chilli',        'காய்ந்த மிளகாய்',     'vegetable', 200.00, '🌶️'),
  ('Bitter Gourd',      'பாகற்காய்',          'vegetable', 40.00,  '🥒'),
  ('Bottle Gourd',      'சுரைக்காய்',          'vegetable', 20.00,  '🥒'),
  ('Ridge Gourd',       'பீர்க்கங்காய்',        'vegetable', 30.00,  '🥒'),
  ('Snake Gourd',       'புடலங்காய்',          'vegetable', 25.00,  '🥒'),
  ('Ash Gourd',         'பூசணிக்காய்',         'vegetable', 15.00,  '🥒'),
  ('Pumpkin',           'மஞ்சள் பூசணி',       'vegetable', 20.00,  '🎃'),
  ('Sweet Potato',      'சர்க்கரைவள்ளி கிழங்கு', 'vegetable', 35.00,  '🍠'),
  ('Yam',               'சேனைக்கிழங்கு',       'vegetable', 40.00,  '🌱'),
  ('Colocasia (Taro)',  'சேப்பங்கிழங்கு',      'vegetable', 30.00,  '🌱'),
  ('Radish',            'முள்ளங்கி',           'vegetable', 20.00,  '🌱'),
  ('Beetroot',          'பீட்ரூட்',            'vegetable', 30.00,  '🟣'),
  ('Turnip',            'டர்னிப்',            'vegetable', 25.00,  '🌱'),
  ('Corn',              'சோளம்',              'vegetable', 20.00,  '🌽'),
  ('Mushroom',          'காளான்',             'vegetable', 150.00, '🍄'),
  ('Spring Onion',      'வெங்காயத்தாள்',      'vegetable', 30.00,  '🧅'),
  ('Leek',              'லீக்ஸ்',              'vegetable', 40.00,  '🌿'),
  ('Celery',            'செலரி',              'vegetable', 60.00,  '🌿'),
  ('Cucumber',          'வெள்ளரிக்காய்',        'vegetable', 20.00,  '🥒'),
  ('Zucchini',          'சுக்கிணி',            'vegetable', 50.00,  '🥒'),
  ('Drumstick',         'முருங்கைக்காய்',        'vegetable', 60.00,  '🌿'),
  ('Raw Banana',        'வாழக்காய்',          'vegetable', 30.00,  '🍌'),
  ('Raw Papaya',        'பப்பாளிக்காய்',        'vegetable', 25.00,  '🌱'),
  ('Cluster Beans',     'கொத்தவரங்காய்',      'vegetable', 50.00,  '🫘'),
  ('Flat Beans',        'அவரைக்காய்',          'vegetable', 45.00,  '🫘'),
  ('Fenugreek Leaves',  'வெந்தயக் கீரை',       'vegetable', 20.00,  '🌿'),
  ('Shallots (Small Onion)', 'சின்ன வெங்காயம்', 'vegetable', 60.00,  '🧅'),
  ('Chayote (Chow Chow)',    'சௌ சௌ',          'vegetable', 35.00,  '🍐'),
  ('French Beans',           'பிரெஞ்ச் பீன்ஸ்',   'vegetable', 60.00,  '🫘'),
  ('Palak (Spinach)',        'பாலக்கீரை',       'vegetable', 30.00,  '🥬'),
  ('Mint Leaves (Pudina)',   'புதினா',          'vegetable', 40.00,  '🌿'),
  ('Coriander Leaves',       'கொத்தமல்லி',       'vegetable', 40.00,  '🌿');

INSERT INTO items (name, name_ta, category, price_per_kg, emoji) VALUES
  ('Mango',          'மாம்பழம்',         'fruit', 80.00,  '🥭'),
  ('Apple',          'ஆப்பிள்',           'fruit', 150.00, '🍎'),
  ('Banana',         'வாழைப்பழம்',       'fruit', 40.00,  '🍌'),
  ('Grapes',         'திராட்சை',          'fruit', 80.00,  '🍇'),
  ('Orange',         'ஆரஞ்சு',           'fruit', 60.00,  '🍊'),
  ('Papaya',         'பப்பாளி',          'fruit', 35.00,  '🫐'),
  ('Watermelon',     'தர்பூசணி',          'fruit', 20.00,  '🍉'),
  ('Muskmelon',      'முலாம்பழம்',        'fruit', 30.00,  '🍈'),
  ('Pineapple',      'அன்னாசி',          'fruit', 50.00,  '🍍'),
  ('Pomegranate',    'மாதுளை',           'fruit', 120.00, '🍎'),
  ('Guava',          'கொய்யா',           'fruit', 50.00,  '🍐'),
  ('Sapota (Chikoo)','சப்போட்டா',        'fruit', 60.00,  '🟤'),
  ('Coconut',        'தேங்காய்',          'fruit', 30.00,  '🥥'),
  ('Lemon',          'எலுமிச்சை',        'fruit', 80.00,  '🍋'),
  ('Lime',           'பச்சை எலுமிச்சை',   'fruit', 60.00,  '🟢'),
  ('Strawberry',     'ஸ்ட்ராபெர்ரி',     'fruit', 200.00, '🍓'),
  ('Kiwi',           'கிவி',              'fruit', 250.00, '🥝'),
  ('Pear',           'பேரிக்காய்',        'fruit', 100.00, '🍐'),
  ('Peach',          'பீச்',              'fruit', 150.00, '🍑'),
  ('Plum',           'பிளம்ஸ்',           'fruit', 120.00, '🟣'),
  ('Cherry',         'செர்ரி',            'fruit', 300.00, '🍒'),
  ('Fig',            'அத்திப்பழம்',       'fruit', 200.00, '🟤'),
  ('Dragon Fruit',   'டிராகன் பழம்',      'fruit', 200.00, '🐉'),
  ('Avocado',        'வெண்ணெய் பழம்',     'fruit', 250.00, '🥑'),
  ('Jackfruit',      'பலாப்பழம்',        'fruit', 40.00,  '🍈'),
  ('Custard Apple',  'சீதாப்பழம்',       'fruit', 80.00,  '🍏'),
  ('Star Fruit',     'விளிம்பிப் பழம்',    'fruit', 60.00,  '⭐'),
  ('Passion Fruit',  'பாஷன் ஃப்ரூட்',    'fruit', 150.00, '🟡'),
  ('Tamarind',       'புளி',              'fruit', 100.00, '🟤'),
  ('Amla (Gooseberry)', 'நெல்லிக்காய்',   'fruit', 60.00,  '🟢'),
  ('Dates',          'பேரீச்சம்பழம்',     'fruit', 200.00, '🟤'),
  ('Litchi',         'லிச்சி',            'fruit', 120.00, '🔴');

INSERT INTO items (name, name_ta, category, price_per_kg, emoji) VALUES
  ('Rice',                   'அரிசி',                 'grocery', 60.00,  '🌾'),
  ('Boiled Rice',            'புழுங்கல் அரிசி',        'grocery', 55.00,  '🍚'),
  ('Raw Rice',               'பச்சரிசி',              'grocery', 60.00,  '🍚'),
  ('Idli Rice',              'இட்லி அரிசி',           'grocery', 50.00,  '🍚'),
  ('Basmati Rice',           'பாசுமதி அரிசி',         'grocery', 120.00, '🍚'),
  ('Wheat',                  'கோதுமை',               'grocery', 40.00,  '🌾'),
  ('Wheat Flour',            'கோதுமை மாவு',           'grocery', 50.00,  '🌾'),
  ('Maida / Refined Flour',  'மைதா',                  'grocery', 45.00,  '🥣'),
  ('Semolina / Rava',        'ரவை',                  'grocery', 55.00,  '🥣'),
  ('Pearl Millet',           'கம்பு',                 'grocery', 40.00,  '🌾'),
  ('Finger Millet / Ragi',   'கேழ்வரகு',             'grocery', 50.00,  '🌾'),
  ('Sorghum / Jowar',        'சோளம்',                'grocery', 45.00,  '🌽'),
  ('Foxtail Millet',         'தினை',                 'grocery', 80.00,  '🌾'),
  ('Little Millet',          'சாமை',                 'grocery', 90.00,  '🌾'),
  ('Kodo Millet',            'வரகு',                 'grocery', 85.00,  '🌾'),
  ('Barnyard Millet',        'குதிரைவாலி',           'grocery', 95.00,  '🌾'),
  ('Oats',                   'ஓட்ஸ்',                 'grocery', 120.00, '🥣'),
  ('Flattened Rice / Poha',  'அவல்',                 'grocery', 50.00,  '🥣'),
  ('Corn Flour',             'சோள மாவு',             'grocery', 60.00,  '🌽'),
  ('Gram Flour / Besan',     'கடலை மாவு',            'grocery', 90.00,  '🟡'),
  ('Rice Flour',             'அரிசி மாவு',            'grocery', 55.00,  '🍚'),
  ('Urad Flour',             'உளுந்து மாவு',          'grocery', 140.00, '⚪'),
  ('Toor Dal',               'துவரம் பருப்பு',         'grocery', 150.00, '🟡'),
  ('Moong Dal',              'பாசிப்பருப்பு',         'grocery', 120.00, '🟡'),
  ('Green Gram',             'பாசிப்பயறு',            'grocery', 110.00, '🟢'),
  ('Urad Dal',               'உளுத்தம் பருப்பு',       'grocery', 140.00, '⚪'),
  ('Chana Dal',              'கடலைப் பருப்பு',        'grocery', 95.00,  '🟡'),
  ('Horse Gram',             'கொள்ளு',                'grocery', 80.00,  '🟤'),
  ('Masoor Dal',             'மசூர் பருப்பு',          'grocery', 100.00, '🟠'),
  ('Peas',                   'பட்டாணி',               'grocery', 70.00,  '🫛'),
  ('White Chickpeas',        'வெள்ளை கொண்டைக்கடலை',   'grocery', 130.00, '⚪'),
  ('Black Chickpeas',        'கருப்பு கொண்டைக்கடலை',   'grocery', 90.00,  '🟤'),
  ('Kidney Beans',           'ராஜ்மா',               'grocery', 140.00, '🫘'),
  ('Black-Eyed Peas',        'காராமணி',              'grocery', 110.00, '🫘'),
  ('Field Beans',            'மொச்சை',               'grocery', 100.00, '🫘'),
  ('Soybeans',               'சோயா பீன்ஸ்',          'grocery', 90.00,  '🫘'),
  ('Salt',                   'உப்பு',                 'grocery', 20.00,  '🧂'),
  ('Sugar',                  'சர்க்கரை',             'grocery', 45.00,  '🍬'),
  ('Jaggery',                'வெல்லம்',               'grocery', 70.00,  '🟤'),
  ('Dry Red Chilli',         'மிளகாய்',               'grocery', 220.00, '🌶️'),
  ('Chilli Powder',          'மிளகாய்த்தூள்',         'grocery', 260.00, '🌶️'),
  ('Black Pepper',           'மிளகு',                 'grocery', 650.00, '⚫'),
  ('Pepper Powder',          'மிளகுத்தூள்',           'grocery', 700.00, '⚫'),
  ('Turmeric',               'மஞ்சள்',                'grocery', 160.00, '🟡'),
  ('Turmeric Powder',        'மஞ்சள் தூள்',           'grocery', 190.00, '🟡'),
  ('Cumin',                  'சீரகம்',                'grocery', 320.00, '🌾'),
  ('Coriander Seeds',        'தனியா',                 'grocery', 140.00, '🌿'),
  ('Coriander Powder',       'தனியாத்தூள்',           'grocery', 160.00, '🌿'),
  ('Fennel Seeds',           'சோம்பு',                'grocery', 220.00, '🌿'),
  ('Fenugreek',              'வெந்தயம்',              'grocery', 100.00, '🌾'),
  ('Mustard Seeds',          'கடுகு',                 'grocery', 110.00, '⚫'),
  ('Fennel',                 'பெருஞ்சீரகம்',          'grocery', 240.00, '🌿'),
  ('Ajwain / Carom Seeds',   'ஓமம்',                 'grocery', 250.00, '🌾'),
  ('Cardamom',               'ஏலக்காய்',              'grocery', 1600.00,'🟢'),
  ('Cloves',                 'கிராம்பு',              'grocery', 900.00, '🟤'),
  ('Cinnamon',               'பட்டை',                 'grocery', 550.00, '🪵'),
  ('Bay Leaf',               'பிரியாணி இலை',          'grocery', 200.00, '🍃'),
  ('Star Anise',             'அன்னாசிப்பூ',           'grocery', 800.00, '⭐'),
  ('Nutmeg',                 'ஜாதிக்காய்',            'grocery', 1100.00,'🟤'),
  ('Mace',                   'ஜாதிபத்திரி',           'grocery', 1800.00,'🍁'),
  ('Poppy Seeds',            'கசகசா',                 'grocery', 1400.00,'⚪'),
  ('Sesame Seeds',           'எள்',                   'grocery', 180.00, '⚫'),
  ('Asafoetida',             'பெருங்காயம்',           'grocery', 650.00, '🟤'),
  ('Curry Leaves',           'கறிவேப்பிலை',           'grocery', 40.00,  '🍃'),
  ('Dried Fenugreek Leaves', 'கசூரி மேத்தி',          'grocery', 300.00, '🍃'),
  ('Cooking Oil',            'சமையல் எண்ணெய்',        'grocery', 150.00, '🫙'),
  ('Sesame Oil',             'நல்லெண்ணெய்',          'grocery', 280.00, '🫙'),
  ('Coconut Oil',            'தேங்காய் எண்ணெய்',      'grocery', 220.00, '🥥'),
  ('Groundnut Oil',          'கடலை எண்ணெய்',          'grocery', 190.00, '🫙'),
  ('Sunflower Oil',          'சூரியகாந்தி எண்ணெய்',   'grocery', 140.00, '🌻'),
  ('Olive Oil',              'ஆலிவ் எண்ணெய்',         'grocery', 600.00, '🫒'),
  ('Ghee',                   'நெய்',                  'grocery', 550.00, '🧈'),
  ('Butter',                 'வெண்ணெய்',              'grocery', 480.00, '🧈'),
  ('Coconut',                'தேங்காய்',              'grocery', 30.00,  '🥥'),
  ('Coconut Milk',           'தேங்காய்ப்பால்',         'grocery', 120.00, '🥥'),
  ('Tamarind',               'புளி',                  'grocery', 110.00, '🟤'),
  ('Tomato Sauce',           'தக்காளி சாஸ்',          'grocery', 130.00, '🥫'),
  ('Soy Sauce',              'சோயா சாஸ்',            'grocery', 120.00, '🍾'),
  ('Vinegar',                'வினிகர்',               'grocery', 60.00,  '🍶'),
  ('Pickle',                 'ஊறுகாய்',              'grocery', 150.00, '🫙'),
  ('Papad',                  'அப்பளம்',               'grocery', 120.00, '🫓'),
  ('Vadam',                  'வடகம்',                 'grocery', 140.00, '🫓'),
  ('Idli Powder',            'இட்லி பொடி',            'grocery', 180.00, '🥣'),
  ('Sambar Powder',          'சாம்பார் பொடி',         'grocery', 220.00, '🥣'),
  ('Rasam Powder',           'ரசப்பொடி',              'grocery', 220.00, '🥣'),
  ('Garam Masala',           'கரம் மசாலா',            'grocery', 350.00, '🌶️'),
  ('Biryani Masala',         'பிரியாணி மசாலா',        'grocery', 350.00, '🍛');

INSERT INTO items (name, name_ta, category, price_per_kg, emoji) VALUES
  ('Milk',                   'பால்',                  'dairy', 50.00,  '🥛'),
  ('Curd / Yogurt',          'தயிர்',                 'dairy', 40.00,  '🥣'),
  ('Buttermilk',             'மோர்',                  'dairy', 25.00,  '🥛'),
  ('Butter',                 'வெண்ணெய்',              'dairy', 480.00, '🧈'),
  ('Ghee',                   'நெய்',                  'dairy', 550.00, '🧈'),
  ('Paneer',                 'பன்னீர்',               'dairy', 350.00, '🧀'),
  ('Cheese',                 'சீஸ்',                  'dairy', 450.00, '🧀'),
  ('Cream',                  'கிரீம்',                'dairy', 200.00, '🥛'),
  ('Condensed Milk',         'கண்டென்ஸ்டு மில்க்',     'dairy', 160.00, '🥫'),
  ('Milk Powder',            'பால் பவுடர்',            'dairy', 300.00, '🥛');

INSERT INTO items (name, name_ta, category, price_per_kg, emoji) VALUES
  ('Cashew',                 'முந்திரி',              'nuts', 800.00,  '🥜'),
  ('Almond',                 'பாதாம்',                'nuts', 750.00,  '🥜'),
  ('Pistachio',              'பிஸ்தா',                'nuts', 950.00,  '🥜'),
  ('Walnut',                 'வால்நட்',                'nuts', 900.00,  '🧠'),
  ('Peanuts',                'நிலக்கடலை',              'nuts', 140.00,  '🥜'),
  ('Raisins',                'உலர் திராட்சை',          'nuts', 320.00,  '🍇'),
  ('Dates',                  'பேரீச்சம்பழம்',          'nuts', 280.00,  '🌴'),
  ('Figs',                   'அத்திப்பழம்',            'nuts', 600.00,  '🟤'),
  ('Almonds (Badam Paruppu)','பாதாம் பருப்பு',         'nuts', 750.00,  '🥜'),
  ('Pumpkin Seeds',          'பூசணி விதை',             'nuts', 450.00,  '🎃'),
  ('Sunflower Seeds',        'சூரியகாந்தி விதை',       'nuts', 350.00,  '🌻'),
  ('Chia Seeds',             'சியா விதை',              'nuts', 400.00,  '⚫'),
  ('Flax Seeds',             'ஆளி விதை',               'nuts', 250.00,  '🟤');



